# Generated by Django 5.0.6 on 2024-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_user_phone_number_user_subject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='تم الدفع'),
        ),
       
    ]
