# Generated by Django 5.0.6 on 2024-07-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0016_user_student_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_type',
            field=models.CharField(choices=[('all', 'مشترك أساسي'), ('part', 'مشترك جزئي')], default='all', max_length=20, verbose_name='نوع اشتراك الطالب'),
        ),
    ]
