# Generated by Django 5.0.6 on 2024-09-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0019_subject_remove_user_subject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
