# Generated by Django 5.0.6 on 2024-09-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0021_subject_user_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
