# Generated by Django 5.0.6 on 2024-09-04 22:58

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0022_user_device_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='اسم الباقة')),
                ('price', models.IntegerField(verbose_name='السعر')),
                ('points', markdownx.models.MarkdownxField(verbose_name='المميزات')),
            ],
            options={
                'verbose_name': 'الباقات والخصومات',
                'verbose_name_plural': 'الباقات والخصومات',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.package', verbose_name='Package'),
        ),
    ]
