# Generated by Django 5.0.6 on 2024-09-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0024_remove_subject_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
