# Generated by Django 5.0.6 on 2024-09-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0025_user_device_info_user_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
