# Generated by Django 5.0.6 on 2024-09-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0026_user_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_info',
        ),
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
