# Generated by Django 5.0.6 on 2024-09-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0027_remove_user_device_info_user_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_type',
            field=models.CharField(blank=True, choices=[('all', 'مشترك أساسي'), ('part', 'مشترك جزئي')], default='all', max_length=20, null=True, verbose_name='نوع اشتراك الطالب'),
        ),
    ]
