# Generated by Django 5.0.6 on 2024-09-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0028_alter_user_student_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_id',
        ),
    ]
