# Generated by Django 5.0.6 on 2024-09-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0029_remove_user_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='url',
        ),
    ]
