# Generated by Django 5.0.6 on 2024-09-19 21:10

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0030_remove_subject_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/',verbose_name='الملف'),
        ),
    ]
