# Generated by Django 5.0.6 on 2024-09-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0031_alter_subject_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='غلاف المادة'),
        ),
    ]
