# Generated by Django 5.0.6 on 2024-09-22 20:19

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0032_subject_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='pdf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رابط الملف '),
        ),
    ]
